services:
  spark-iceberg:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-iceberg
    environment:
      - SPARK_CONF_DIR=/opt/spark/conf
      # AWS Credentials (montadas via volume)
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - spark-warehouse:/home/iceberg/warehouse
      - ../../src:/opt/spark-apps/src
      - ../../data:/opt/spark-apps/data
      - ~/.aws:/home/spark/.aws:ro
    command: >
      bash -c "
        /opt/spark/sbin/start-master.sh &&
        tail -f /opt/spark/logs/*
      "
    networks:
      - iceberg-net

volumes:
  spark-warehouse:
    driver: local

networks:
  iceberg-net:
    driver: bridge